[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/digital/post/*"
  to = "/digital/blog/:splat"
  status = 301
  force = true

# New redirects for folder changes
[[redirects]]
  from = "/webflow-agency/*"
  to = "/webflow-republic/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/saas-growth-services/*"
  to = "/growth-consulate/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/case-studies/*"
  to = "/success-missions/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/company/*"
  to = "/agency/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/IMB-Files/*"
  to = "/IMB-X-Files/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/IMB-X-Files/65f43207d485843526415f97/*"
  to = "/IMB-X-Files/The-Ambassadors-Assets/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/IMB-X-Files/65f43207d485843526415f76/*"
  to = "/IMB-X-Files/The-IMB-Images/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"  # Replace with your actual build command if applicable
  publish = "public"         # Replace with your publish directory

[build.processing]
  css = { minify = true }    # Enable CSS minification
  js = { minify = true }     # Enable JavaScript minification
  images = { optimize = true } # Enable image optimization